security:
    encoders:
        CuteFlow\CoreBundle\Entity\User: md5

    role_hierarchy:
        ROLE_CUTEFLOW_ADMIN:       ROLE_CUTEFLOW_USER

    providers:
        main:
            id: cuteflow.user_manager

    firewalls:
        profiler:
            pattern:  ^/_profiler
            security: false

        wdt:
            pattern:  ^/_wdt
            security: false
            
        css:
            pattern: /css/.*
            security: false
            
        login:
            pattern:  ^/login$
            security: false

        user:
            pattern: /user
            security: false
            
        main:
            pattern:      /.*
            form_login:   
                check_path: /login_check
                login_path: /login
                success_handler: cuteflow.login_success
            logout:       
                path:   /logout
                target: /
                invalidate_session: true
        

    access_control:
        - { path: /.*, roles: ROLE_CUTEFLOW_USER }
        - { path: /admin, roles: ROLE_CUTEFLOW_ADMIN }
